#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, in2,    liftPot,        sensorPotentiometer)
#pragma config(Sensor, in3,    clawR,          sensorPotentiometer)
#pragma config(Sensor, in4,    clawL,          sensorPotentiometer)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           clawL,         tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           backLeftDrive, tmotorVex393HighSpeed_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port3,           backRightDrive, tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port4,           arm4,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           arm2,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           frontLeftDrive, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           arm3,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           arm5,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           frontRightDrive, tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          clawR,         tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"
#include "563 Functions V2.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	openClaw();
	driveForward(127, 100);
	lift(70);
	wait1Msec(1100);
	haltYo();
	wait1Msec(100);
	driveForward(127, 1100);
	haltYo();
	driveBackward(70, 700);
	haltYo();
	lift(-75);
	wait1Msec(500);
	haltYo();
	pointTurn(75, 300, RIGHT);
	haltYo();
	driveForward(90, 800);
	closeClaw();
	lift(127);
	wait1msec(500);
	haltYo();
	liftStall(10);
	pointTurn(75,300, RIGHT);
	lift(127);
	driveBackward(75, 700);
	openClaw();
	lift(-127);
	wait1Msec(500);
	haltYo();
	openClaw();
	driveForward(80, 800);
	closeClaw();
	wait1Msec(100);
	lift(127);
	driveBackward(127, 1000);
	openClaw();
	haltYo();


}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	iDes = (SensorValue [in3]);
  while (true)
  {
			//startTask (clawControll);
			startTask (claw);
			drive();

		while(vexRT[Btn6U])
		{
			drive();
			lift(127);
		}
		liftStall(10);


		while(vexRT[Btn6D])
		{
			drive();
			lift(-50);
		}

		while(vexRT[Btn7D])
		{
			drive();
			lift(-127);
		}

		while(vexRT[Btn8U])
		{
			drive();
			while (vexRT[Btn6U])
			{
				lift(127);
			}
		}
		while(vexRT[Btn5D])
		{
			drive();

		}
  }
}
